let myDate=new Date()
console.log(myDate.getTime())
console.log(myDate.getFullYear())
console.log(myDate.getMonth())
console.log(myDate.getDate())
console.log(myDate.getDay())
console.log(myDate.toLocaleDateString())
console.log(myDate.toLocaleTimeString())
console.log(myDate.toString())
console.log(myDate.toLocaleString())
console.log(typeof myDate)
console.log(typeof myDate.toLocaleDateString())
let myCreatedDate=new Date(2003,7,31);
console.log(typeof myCreatedDate.toLocaleDateString())
console.log(myCreatedDate.toLocaleTimeString())
console.log(typeof myCreatedDate.toString())
console.log(myCreatedDate.toDateString())
console.log(typeof myCreatedDate.toLocaleDateString())

let timestamp=Date.now()
console.log(timestamp)
console.log(myCreatedDate.getTime())
console.log(typeof timestamp)
console.log(typeof myCreatedDate.toLocaleDateString())

